### ISSUE TITLE
Links in the GESIS blog post not working

### ISSUE THREAD

**Issue by arnim** [2i2c-org/2i2c-brochure#139]
### Context

Links in https://2i2c.org/blog/2022/gesis-2i2c-collaboration-update/ are potentially not proper in the [Markdown](https://github.com/2i2c-org/2i2c-org.github.io/blob/main/content/blog/2022/gesis-2i2c-collaboration-update/index.md) e.g. 

> Mybinder.org

links in the post to 

> https://github.com/2i2c-org/2i2c-org.github.io/blob/main/content/blog/2022/gesis-2i2c-collaboration-update/mybinder.org

**Comment by choldgraf** [comment]
Hmmm it seems our link checker is not working we expected then 🤔

**Comment by damianavila** [comment]
Thanks @choldgraf for the fix and @arnim for the report!
