### ISSUE TITLE
Our linkchecker is broken

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/2i2c-brochure#144]
We have a linkchecker running on a github action each day, here's an example of the job:

https://github.com/2i2c-org/2i2c-org.github.io/actions/runs/3959087946

However, it is passing when we actually have broken links. This is a problem! We should figure out why it is passing even though our links aren't working in some cases.

Here's the configuration for the checker job:

https://github.com/2i2c-org/2i2c-org.github.io/blob/main/.github/workflows/linkcheck.yml

**Comment by sgibson91** [comment]
<img width="1260" alt="Screenshot 2023-05-05 at 07 03 30" src="https://user-images.githubusercontent.com/44771837/236387118-6bbb4811-e6b3-4d50-8035-0b43df1f9254.png">

The CI job is having trouble starting for me

**Comment by choldgraf** [comment]
here's a little analysis of what's going on...I'm not sure how to fix it though:

- https://github.com/2i2c-org/2i2c-org.github.io/issues/159

I opened a separate issue because I think it's actually not related to this issue, yay compounding and independent issues!
