### ISSUE TITLE
Alias '/careers' -> '/jobs' not working

### ISSUE THREAD

**Issue by tylere** [2i2c-org/2i2c-brochure#151]
The [alias '/careers'](https://github.com/2i2c-org/2i2c-org.github.io/blob/main/content/jobs/_index.md?plain=1#L3) for the /jobs page doesn't seem to be working correctly.

For example, the link to `https://2i2c.org/careers/` on the [Get Involved](https://github.com/2i2c-org/2i2c-org.github.io/blob/main/content/mission/getinvolved.md?plain=1#L21) section results in a 404 page.

**Comment by choldgraf** [comment]
Thank you so much for spotting these link bugs!
