### ISSUE TITLE
Add Harold and Angus to our team page

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/2i2c-brochure#210]
Our [team page here](https://2i2c.org/organization/) needs to be updated with @haroldcampbell and @agoose77 . This is a ticket to track this.

Here's the folder where we'll need to add new entries for Harold/Angus:

https://github.com/2i2c-org/2i2c-org.github.io/tree/main/content/authors

**Comment by agoose77** [comment]
Thanks Chris — I'll update my entry. I can update @haroldcampbell's too, although I suspect he would like to do that himself? :)
