### ISSUE TITLE
Post our GESIS blog post on social media

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/2i2c-brochure#214]
https://2i2c.org/blog/2024/jupyterhub-binderhub-gesis/ has been published now, but needs to be posted on our various social media accounts. We don't currently have a written down process for this. I'd like us to post this out without waiting for a process to be written down, but just flagging it.

1. Write out the blurb to be posted
2. Post it.

I can probably help with (1) but would need someone else to do (2).

**Comment by yuvipanda** [comment]
We should also tag our partners - https://github.com/2i2c-org/2i2c-org.github.io/pull/205#issuecomment-1890152748 from @arnim lists them.

**Comment by jnywong** [comment]
Here's a quick pass on a blurb:

_Twitter/X and Mastodon (short form, 280 & 500 characters respectively)_

> Do you enjoy the simplicity of sharing your Jupyter Notebooks on BinderHub but also want to use it to customise software envs for interactive computing w/ persistent storage on the cloud? What if we combined it with JupyterHub? Read on to find out more 🔍 https://2i2c.org/blog/2024/jupyterhub-binderhub-gesis/

> With thanks to @gesis_org @nfdi4ds @CESSDA_Data #openscience #opensource #reproducibility

_LinkedIn, etc. (long form)_

> Do you enjoy the simplicity of sharing your Jupyter Notebooks on BinderHub but wish you could also use it to customise software environments for interactive computing (and with persistent storage!) on the cloud? What if we integrated BinderHub and JupyterHub together to empower users to manage their own environments without the need to rely on the JupyterHub admin? Read our blog post to find out more! 

@yuvipanda I can post on all 2i2c social media once you approve the blurb text 📮

**Comment by yuvipanda** [comment]
@jnywong that's an amazing blurb! Please do post.

**Comment by jnywong** [comment]
Done!

- LinkedIn https://www.linkedin.com/feed/update/urn:li:activity:7153822966114381824
- Twitter/X https://x.com/2i2c_org/status/1748056493180453043?s=20
- Mastodon https://hachyderm.io/@2i2c_org/111778471452210633

🎉

**Comment by yuvipanda** [comment]
Amazing work, thank you so much @jnywong!

**Comment by yuvipanda** [comment]
@jnywong do you think you can tag the partners on twitter? I don't know if they have mastodon accounts, but I think they may have twitter ones? 

/cc @arnim - do you know if there are any with mastodon accounts?

**Comment by arnim** [comment]
There are mastodon accounts

@GESIS@sciences.social
@NFDI4DS@nfdi.social and @NFDI@nfdi.social

Didn't share them since I assumed you would do twitter & co.  and I would mastodon to share this a bit. Would you mind if I do the mastodon thing?

**Comment by yuvipanda** [comment]
@arnim please go for it! We'll also edit ours later to include the partner mastodon links.

**Comment by arnim** [comment]
And my mastodon post 🎉 
Feel free to share :)
https://mas.to/@arnim/111779246189215252

**Comment by jnywong** [comment]
Okay nice, thanks for the Mastodon post! 

> @jnywong do you think you can tag the partners on twitter?

Nw Yuvi, that was done in the original post 😄

**Comment by yuvipanda** [comment]
@jnywong ah ty! My network blocks were far too strong for me to check :) 

And thank you so much for getting these out!
