### ISSUE TITLE
[BLOG] Sloan Foundation Awards $1.125M to STRUDEL to Enhance UX in Scientific Software Development

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/2i2c-brochure#304]
### Context

| Name | Value |
| --- | --- |
| Title | Sloan Foundation Awards $1.125M to STRUDEL to Enhance UX in Scientific Software Development |
| Description | 
|
| Featured image/thumbnail |  |
| Notes | https://sloan.org/grant-detail/G-2024-22557
 |
| **Publish date** | 2024-09-13 |

### Metadata & Acknowledgements

| Name | Value |
| --- | --- |
| Tags | open-source |
| People |  |
| Affiliations |  |
| Open-source software |  |
[^1]: **DO NOT EDIT DIRECTLY**. This issue body was automatically generated. Make edits at [the AirTable record](﻿https://airtable.com/appM2L2x1uglMU0hy/tbl7ekka6VQREZ00V/recq3eMlIV3mfKSxs﻿) and they'll be reflected here.

**Comment by jnywong** [comment]
Test AirTable automation.
