### ISSUE TITLE
[2024-09-13] Sloan Foundation Awards $1.125M to STRUDEL to Enhance UX in Scientific Software Development

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/2i2c-brochure#305]
### Context

| Name | Value |
| --- | --- |
| Title | Sloan Foundation Awards $1.125M to STRUDEL to Enhance UX in Scientific Software Development |
| Description |  |
| Notes | |
| AirTable[^1] | [AirTable record](https://airtable.com/appM2L2x1uglMU0hy/tbl7ekka6VQREZ00V/recq3eMlIV3mfKSxs) |
| **Publish date** | 2024-09-13 |

### Metadata & Acknowledgements

| Name | Value |
| --- | --- |
| Tags | open-source |
| People |  |
| Affiliations |  |
| Open-source software |  |

![](https://v5.airtableusercontent.com/v3/u/33/33/1726236000000/grSvgxosKOAuYDw8DhauHA/f25yalSdVyU9LYPz9FvV0uhSM_HSUhKt598cSinCDAyFJuhnArusEMi68d76g_fB2EWYJsrwichWZ2ewJvAEyfH3BEEleAxrlTRQg0o3t2l6KCvjQ-rtPOykzJGVwUUgMIjKlBLFxa_8G8jSu7aOm7GU1pJ3r7gI0JuHVuzDxcFCwGC5izbmKqiasEb6XSzL/k40-WmteysNOQxG6OBh7XzAwKyOG9W2ASjUOQCFsv04)

[^1]: **DO NOT EDIT DIRECTLY**. This issue body was automatically generated. Make edits at [the AirTable record](﻿https://airtable.com/appM2L2x1uglMU0hy/tbl7ekka6VQREZ00V/recq3eMlIV3mfKSxs﻿) and they'll be reflected here.

**Comment by jnywong** [comment]
Testing AirTable automation.
